### ISSUE TITLE
userpage: Infinite redirect if logged in

### ISSUE THREAD

**Issue by sophie-h** [flathub/website#555] opened 2022-08-09 16:10 UTC
The title of one page in the redirect chain says something like

>  Application error: a client-side exception has occurred

I'm logged in via GitHub. The browser is Chromium 102.

[Screencast from 09.08.2022 18:00:03.webm](https://user-images.githubusercontent.com/3466497/183702815-236a8e50-1c01-4a34-92ba-3da4605009af.webm)

**Comment by razzeee** [comment] 2022-08-09 18:08
Could be due to https://github.com/flathub/website/pull/528

@kymckay

**Comment by kymckay** [comment] 2022-08-09 20:53
Hmm, just thinking through the redirects involved:

-  `/userpage` is using `LoginGuard` which would redirect to `/login` if `/userinfo` API request reports that you're logged out.
- `/login` would redirect to `/userpage` if `/userinfo` API request reported that you're logged in.

There's potentially some sort of redirect feedback loop going on there, but off the top of my head I can't think how the user context could be reporting those two exclusive states in the same session (unless it is somehow updating with each redirect).

I likely won't have time to investigate until next week at earliest (because my MSc dissertation is due on Monday).

@sophie-h If you can repeat this, it would narrow down the cause to know:

- What does your browser history show when it happens? Is it alternating between two pages repeatedly?
- If you check the networking tab of browser tools when this happens, do you see many requests to a `/userinfo` API endpoint?

**Comment by sophie-h** [comment] 2022-08-09 21:00
Start Page -> klick on my name on the top right -> click on my app -> click on my name on the top right

And then it does not load the user page again.

![Screenshot from 2022-08-09 22-55-00](https://user-images.githubusercontent.com/3466497/183760389-dc0696de-ce20-48ac-a77d-2a8f31505eac.png)

**Comment by kymckay** [comment] 2022-08-09 21:09
Thanks! That confirms my suspicion that is the `/userinfo` DDOS-behaviour bug we've been seeing and probably not due to redirects (though won't rule that out as the cause, I hadn't considered the possible loop there before).

Glad to confirm you also only seem to induce this upon the second visit to the user page, that's something I've been meaning to confirm isn't just me. This is an odd one, it doesn't seem to happen in the development environment, only reproducible in staging currently (though I'm confident it's not the fault of the environment, and just some implicit behaviour which hides the bug when running locally).

**Comment by sophie-h** [comment] 2022-08-09 21:34
I was convinced of redirects because the title in the tab was constantly changing and afterward confirmation bias did its job xD

Good luck with uni btw

**Comment by kymckay** [comment] 2022-08-29 23:40
Was doing some reproduction investigation and noticed that I'm no longer seeing the infinite `/userinfo` requests, but that an appstream request on the userpage is being blocked by CORS (which could explain why the issue is only happening in staging and not development).

![Screenshot from 2022-08-30 00-36-33](https://user-images.githubusercontent.com/5459452/187317331-023f0735-f2b2-4344-913e-1bca04498db6.png)

**Comment by razzeee** [comment] 2022-12-20 17:09
Is this still happening?

**Comment by kymckay** [comment] 2022-12-20 17:45
I was just able to repro this as follows, but it seems to be inconsistent:

1. Log out
2. Hard refresh
3. Log in with Github
4. Go to app listed under "Authored Apps" on my user page (in my case that's https://beta.flathub.org/apps/details/org.flatpak.qtdemo)
5. Go back to user page using top right icon

I see the client error message. Refreshing the page a few times eventually clears it and then it doesn't seem to occur again until I start from step 1 (except now even that is not reproducing it, so either this is intermittent, asynchronous or some old local data was causing it).

**Comment by razzeee** [comment] 2022-12-20 18:45
https://github.com/flathub/website/pull/872 should fix the client error hopefully, but you might need to clear local storage

**Comment by razzeee** [comment] 2022-12-20 18:47
Yeah, what you described, should be fixed by that PR

**Comment by razzeee** [comment] 2023-02-05 13:01
Feel free to reopen this, if it's still happening, but I think the infinite redirect doesn't happen anymore.

**Closed by razzeee** 2023-02-05 13:01 UTC
Labels: before launch
