### ISSUE TITLE
Error click search results

### ISSUE THREAD

**Issue by n3storm** [flathub/website#1709] opened 2023-07-27 08:27 UTC
When searching "thunder" or "thunderbird" clicking on Thunderbird result does nothing. Any other result works right.

(Firefox desktop browser 115.0.2 (64-bit))

**Comment by razzeee** [comment] 2023-07-27 08:31
Duplicate of https://github.com/flathub/website/issues/1581

We hopefully get a new release on the 31st

**Closed by razzeee** 2023-07-27 08:31 UTC
