### ISSUE TITLE
Every app is marked as proprietary

### ISSUE THREAD

**Issue by dtsudo** [flathub/website#1930] opened 2023-09-08 20:10 UTC
Apologies if this has already been posted (though I don't see it in the issues tracker or on https://discourse.flathub.org/).

It seems like every application now has the "proprietary" warning -- e.g.

VLC
![image](https://github.com/flathub/website/assets/13825437/8c6a44cd-f78f-40a9-8f0a-aaadd78ff665)

Firefox
![image](https://github.com/flathub/website/assets/13825437/20d2a7ff-5167-4655-a1a8-e9325d130a9b)

And many others.

It was fine yesterday, so I assume it's caused by a code change on the website.

**Comment by hokonch** [comment] 2023-09-08 20:23
Cause: Poor response to  https://github.com/flathub/website/issues/1918

https://github.com/flathub/website/blob/78b936a1390c9a910bbf548b5eb9684552b7dbf7/frontend/src/components/application/LicenseInfo.tsx#L89

`?? true` is nonsense.

**Comment by pedrolcl** [comment] 2023-09-09 08:28
This is a very serious bug. I hope that it is given top priority and speed to fix it.

**Comment by razzeee** [comment] 2023-09-09 10:25
> Cause: Poor response to #1918
> 
> https://github.com/flathub/website/blob/78b936a1390c9a910bbf548b5eb9684552b7dbf7/frontend/src/components/application/LicenseInfo.tsx#L89
> 
> `?? true` is nonsense.

No, `true` is absolutely what we want, we want unknown states to end up as proprietary software. The problem is clearly not that statement.

**Comment by hfiguiere** [comment] 2023-09-09 12:51
So what the value of `project_license` on these packages?

**Comment by hfiguiere** [comment] 2023-09-09 13:09
For VLC it's `GPL-2.0+`.

Which is a deprecated SPDX identifier but the appstream validation doesn't seem to care.

**Comment by hfiguiere** [comment] 2023-09-09 13:53
it seem it was resolved by itself.

![image](https://github.com/flathub/website/assets/114441/ad92bbf9-b926-450b-9169-c675879a6a8c)

![image](https://github.com/flathub/website/assets/114441/f45e50c1-b16c-4259-ae97-fb69198e673e)

**Comment by guihkx** [comment] 2023-09-09 13:58
Likely resolved by c8045665f3db81fe38307d716318cdf6c3654826.

All my apps show the correct license now.

**Comment by razzeee** [comment] 2023-09-09 14:02
Sorry, for breaking it :/

**Closed by razzeee** 2023-09-09 14:02 UTC
