### ISSUE TITLE
Translation support for app info

### ISSUE THREAD

**Issue by iman-salmani** [flathub/website#1687] opened 2023-07-16 10:45 UTC
It seems the Flathub website does not add translation texts inside metainfo.xml.
For example, ir.imansalmani.IPlan.metainfo.xml should be something like the following code but the information on the [app page](https://flathub.org/fa/apps/ir.imansalmani.IPlan) does not translate.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop">
  <id>ir.imansalmani.IPlan</id>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>GPL-3.0-or-later</project_license>
  <name>IPlan</name>
  <summary>Your plan for improving personal life and workflow</summary>
  <summary xml:lang="tr">Kişisel yaşamınızı ve iş akışınızı iyileştirme planınız</summary>
  <summary xml:lang="pt_BR">Seu planejador para melhorar a vida pessoal e o fluxo de trabalho</summary>
  ...
</component>
```
[steam meta info file](https://github.com/flathub/com.valvesoftware.Steam/blob/beta/com.valvesoftware.Steam.metainfo.xml#L11-L28).

**Comment by iman-salmani** [comment] 2023-07-16 10:54
I tested IPlan in Gnome Software. texts are translated.

**Comment by razzeee** [comment] 2023-07-16 11:25
Duplicate of https://github.com/flathub/website/issues/1058

**Closed by razzeee** 2023-07-16 11:25 UTC
