### ISSUE TITLE
Please show image captions

### ISSUE THREAD

**Issue by ovari** [flathub/website#1536] opened 2023-06-01 22:39 UTC
Images have captions in the AppData file, i.e. https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/org.moneymanagerex.MMEX.metainfo.xml#L281

Not captions are shown in Flathub. Should the caption show when the mouse hovers over the image and/or the caption be shown under the image?
https://flathub.org/en-GB/apps/org.moneymanagerex.MMEX

Thank you

**Comment by razzeee** [comment] 2023-06-02 08:00
They should be shown under the image, but that's currently not possible.

Duplicate of https://github.com/flathub/website/issues/48

**Closed by razzeee** 2023-06-02 08:00 UTC
