### ISSUE TITLE
Expose summary API for all Apps

### ISSUE THREAD

**Issue by JakobDev** [flathub/website#239] opened 2022-05-11 14:08 UTC
I'm the developer of [flathub-data-viewer](https://jakobdev.github.io/flathub-data-viewer), a little tool which shows basic informations about Flathub. It can parse the Appstream Data directly, since it is just a XML file. But for things like Permissions and BaseApp it relays on the summary API of Flathub. But the API currently only supports Desktop Apps. Would be nice, if you could support all Types of Apps.

**Comment by razzeee** [comment] 2022-05-11 23:43
Duplicate of https://github.com/flathub/website/issues/53

**Comment by razzeee** [comment] 2022-11-14 19:10
Btw, some types like plug-ins are not providing summaries at all afaik

**Comment by razzeee** [comment] 2023-06-07 11:20
We're exposing stats for all apps now, but summaries are still a todo.

**Comment by razzeee** [comment] 2023-08-13 14:41
How important would platforms and having .Debug, .Locale and .Sources be?

**Comment by razzeee** [comment] 2023-08-17 21:54
We're now exposing all but .Debug, .Locale, .Sources and Platforms. Platforms are excluded, as they seem to have duplicate keys, which the current library used to parse that ini file format doesn't like.

**Closed** 2023-08-19 22:34 UTC
Labels: after launch
